#pragma once
//EEPROM magic number to indicate valid stored settings
#define EEPROM_MAGIC_ADDRESS 0x01
#define EEPROM_MAGIC_VALUE 0x00

#define SENSOR_A_CALIBRATION_ADDR 1
#define SENSOR_B_CALIBRATION_ADDR 125 //124 + 1
#define SENSOR_C_CALIBRATION_ADDR 249 // 2*124 + 1
#define SENSOR_D_CALIBRATION_ADDR 373 // 3*124 + 1
//Each sensor calibration block is 124 bytes

#define ACTIVE_MIDI_CHANNEL_A_ADDR 374
#define ACTIVE_MIDI_CHANNEL_B_ADDR 375
#define ACTIVE_MIDI_CHANNEL_C_ADDR 376
#define ACTIVE_MIDI_CHANNEL_D_ADDR 377

#define OCTAVE_A_ADDR 378
#define OCTAVE_B_ADDR 379
#define OCTAVE_C_ADDR 380
#define OCTAVE_D_ADDR 381